s o Y t [tol] [to] [to] [to]
z Z [zyo] [yo] [yo] [yo] h [tol]
[to] [to] Z [to] z Z [icE] [iE]
[yw] [yw] h [tol] [to] [to] [to] z
Z [zyo] [yo] [YP] [ZYP] c [siZ] [si]
[iE] [iE] c v [sVO] [icO] [zyi] h
[tol] [to] [to] [to] z Z [zyo] [yo]
l [yok] [yo] h [tol] [to] [to] z
Z [to] z Z [icE] [iE] [iE] J
[iE] Z c [vYP] [YP] [YP] [YP] V
v [siV] [si] v [si] [sic] Z [zyw]
[yw] [yw] [tq] [E(] [vto] [tom] [to] [vto]
[icE] [miE] [iE] [icE] [ZYW] [mYW] [YW] [ZYW]
[zywo] [icV] [zvo] [tsoZ] l [shD] h [ziPE]
J [gdP] h [lYWO] H [sOD] D [ywrod]
[iaH] [ohY] [vto] [tom] [to] [vto] [icE] [miE]
[iE] [icE] [ZYW] [mYW] [YW] [ZYW] [zywo] [icV]
[zvo] [tsoZ] l [shD] h [ziPE] J [gdP]
h [lYWO] H [sOD] D [ywrod] [iaH] [ohY]
[l8] 5 8 w % 5 [l8] 5
8 w % 5 [l(] ^ ( E
7 ^ [Z(] ^ [H(] E [h7] ^
[l8] [G5] [l8] w % [Z5] [l8] [G5]
8 [wl] % [z5] Z [l(] H [^D]
[l(] E 7 [v^] [Z(] [^V] [Z(] E
[J7] ^ [l8] 5 8 w % 5
[l8] 5 8 w % 5 [l(] ^
( E 7 ^ [Z(] ^ [H(] E
[h7] ^ [l8] [G5] [l8] w % [Z5]
[l8] [G5] 8 [wl] % [z5] Z [l(]
H [^D] [l(] E 7 [v^] [Z(] [^V]
[Z(] E [J7] ^ [wl8] [w8] [w8] [w8]
[w8] [w8]
